<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RepositoryUrl>https://github.com/themeldingwars/FauCap</RepositoryUrl>
    <LangVersion>9</LangVersion>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company>TheMeldingWars</Company>
    <AssemblyVersion>1.15.0.0</AssemblyVersion>
    <Version>1.15.0.0</Version>
    <PackageVersion>1.15.0.0</PackageVersion>
  </PropertyGroup>

</Project>
