<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RepositoryUrl>https://github.com/themeldingwars/FauCap</RepositoryUrl>
    <LangVersion>9</LangVersion>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company>TheMeldingWars</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
