<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RepositoryUrl>https://github.com/themeldingwars/FauCap</RepositoryUrl>
    <LangVersion>9</LangVersion>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>The Melding Wars</Authors>
    <Description>Core parsing library behind FauCap for reading Firefall Matrix protocol packet captures.</Description>
    <PackageTags>firefall;pcap;matrix;parser</PackageTags>
    <PackageProjectUrl>https://github.com/themeldingwars/FauCap</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
